### ISSUE TITLE
When will the code be released

### ISSUE THREAD

**Issue by xiangliu886** [gaopengcuhk/Container#1]
Great work! When will the code be released?

**Comment by gaopengcuhk** [comment]
Please share your email. I can send you the code before the official release.

**Comment by xiangliu886** [comment]
xiangliu886@gmail.com. Thank you very much!

**Comment by gaopengcuhk** [comment]
Note that the distributed code is used for replicating results in our arxiv paper, not for the new results. The Container-S in arxiv is 82.0 while in this repo 83.0. 

Thanks for your interest in our work.
